### ISSUE TITLE
Linux Installation

### ISSUE THREAD

**Issue by LizzyTheSnake** [zHappySnake/snakebot#3]
I need help with the installation on a Linux system. When I use `sudo apt install npm` it asks for my password and nothing else happens.

**Comment by zHappySnake** [comment]
You entered the password and nothing happens?

**Comment by LizzyTheSnake** [comment]
When I try to enter something nothing happens

**Comment by zHappySnake** [comment]
You just can't see it. You actually enter stuff, it's just invisible. Enter your password and hit the enter key.

**Comment by LizzyTheSnake** [comment]
ohhh okay, thank you!

**Comment by zHappySnake** [comment]
You're welcome. I will close this case now.
